[[redirects]]
  from = "/*"
  force = true
  status = 200
  conditions = {Role = ["nginx"]}

[[redirects]]
  from = "/*"
  to = "https://customdomain.moneytronicswag.com"
  force = true
  status = 401
